mysql:
  #打开数据库的最大连接数
  max_open_conn: 150
  #连接池中的保持连接的最大连接数
  max_idle_conn: 100
  #链接
  source_name: root:123456@tcp(10.20.29.148:13306)/jenkins?parseTime=true&charset=utf8&loc=Local
#HTTP的链接超时时间++++`
readOut: 15s
#HTTP的链接超时时间
writeOut: 20s
#初始化Http的Server超时时间设置，以秒为单位
server:
  #空闲链接超时时间
  idle_timeout: 300
  #ReadTimeout 包括了 TLS 握手的时间
  read_timeout: 160
  #WriteTimeout 包括了 TLS握手、读取 Header 的时间（虚线部分）
  write_timeout: 180

# HTTP绑定端口
http: 8081

# 日志配置文件
logger_jsonFile: config/log.json















